# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.models.tag_mod_req import TagModReq  # noqa: E501
from cbrain_api.rest import ApiException


class TestTagModReq(unittest.TestCase):
    """TagModReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTagModReq(self):
        """Test TagModReq"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cbrain_api.models.tag_mod_req.TagModReq()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
