# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.sessions_api import SessionsApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestSessionsApi(unittest.TestCase):
    """SessionsApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.sessions_api.SessionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_session_delete(self):
        """Test case for session_delete

        Destroy the current session  # noqa: E501
        """
        pass

    def test_session_get(self):
        """Test case for session_get

        Get session information  # noqa: E501
        """
        pass

    def test_session_post(self):
        """Test case for session_post

        Create a new session  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
