# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.bourreaux_api import BourreauxApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestBourreauxApi(unittest.TestCase):
    """BourreauxApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.bourreaux_api.BourreauxApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bourreaux_get(self):
        """Test case for bourreaux_get

        Get a list of the Bourreaux available to be used by the current user.  # noqa: E501
        """
        pass

    def test_bourreaux_id_get(self):
        """Test case for bourreaux_id_get

        Get information about a Bourreau.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
