# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.tools_api import ToolsApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestToolsApi(unittest.TestCase):
    """ToolsApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.tools_api.ToolsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tools_get(self):
        """Test case for tools_get

        Get the list of Tools.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
