# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.tags_api import TagsApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestTagsApi(unittest.TestCase):
    """TagsApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.tags_api.TagsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tags_get(self):
        """Test case for tags_get

        Get a list of the tags currently in CBRAIN.  # noqa: E501
        """
        pass

    def test_tags_id_delete(self):
        """Test case for tags_id_delete

        Delete a tag.  # noqa: E501
        """
        pass

    def test_tags_id_get(self):
        """Test case for tags_id_get

        Get one tag.  # noqa: E501
        """
        pass

    def test_tags_id_put(self):
        """Test case for tags_id_put

        Update a tag.  # noqa: E501
        """
        pass

    def test_tags_post(self):
        """Test case for tags_post

        Create a new tag.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
