# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.groups_api import GroupsApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.groups_api.GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_get(self):
        """Test case for groups_get

        Get a list of the Groups (projects) available to the current user.  # noqa: E501
        """
        pass

    def test_groups_id_delete(self):
        """Test case for groups_id_delete

        Deletes a Group (project).  # noqa: E501
        """
        pass

    def test_groups_id_get(self):
        """Test case for groups_id_get

        Get information on a Group (project).  # noqa: E501
        """
        pass

    def test_groups_id_put(self):
        """Test case for groups_id_put

        Update the properties of a Group (project).  # noqa: E501
        """
        pass

    def test_groups_post(self):
        """Test case for groups_post

        Creates a new Group.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
