# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.userfiles_api import UserfilesApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestUserfilesApi(unittest.TestCase):
    """UserfilesApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.userfiles_api.UserfilesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_userfiles_change_provider_post(self):
        """Test case for userfiles_change_provider_post

        Moves the Userfiles from their current Data Provider to a new one.  # noqa: E501
        """
        pass

    def test_userfiles_compress_post(self):
        """Test case for userfiles_compress_post

        Compresses many Userfiles each into their own GZIP archive.  # noqa: E501
        """
        pass

    def test_userfiles_delete_files_delete(self):
        """Test case for userfiles_delete_files_delete

        Delete several files that have been registered as Userfiles  # noqa: E501
        """
        pass

    def test_userfiles_download_post(self):
        """Test case for userfiles_download_post

        Download several files  # noqa: E501
        """
        pass

    def test_userfiles_get(self):
        """Test case for userfiles_get

        List of the Userfiles accessible to the current user.  # noqa: E501
        """
        pass

    def test_userfiles_id_content_get(self):
        """Test case for userfiles_id_content_get

        Get the content of a Userfile  # noqa: E501
        """
        pass

    def test_userfiles_id_get(self):
        """Test case for userfiles_id_get

        Get information on a Userfile.  # noqa: E501
        """
        pass

    def test_userfiles_id_put(self):
        """Test case for userfiles_id_put

        Update information on a Userfile.  # noqa: E501
        """
        pass

    def test_userfiles_post(self):
        """Test case for userfiles_post

        Creates a new Userfile and upload its content.  # noqa: E501
        """
        pass

    def test_userfiles_sync_multiple_post(self):
        """Test case for userfiles_sync_multiple_post

        Syncs Userfiles to the local Data Providers cache.  # noqa: E501
        """
        pass

    def test_userfiles_uncompress_post(self):
        """Test case for userfiles_uncompress_post

        Uncompresses many Userfiles.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
