# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cbrain_api
from cbrain_api.api.tasks_api import TasksApi  # noqa: E501
from cbrain_api.rest import ApiException


class TestTasksApi(unittest.TestCase):
    """TasksApi unit test stubs"""

    def setUp(self):
        self.api = cbrain_api.api.tasks_api.TasksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tasks_get(self):
        """Test case for tasks_get

        Get the list of Tasks.  # noqa: E501
        """
        pass

    def test_tasks_id_get(self):
        """Test case for tasks_id_get

        Get information on a Task.  # noqa: E501
        """
        pass

    def test_tasks_post(self):
        """Test case for tasks_post

        Create a new Task.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
