# coding: utf-8

# flake8: noqa
"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from cbrain_api.models.bourreau import Bourreau
from cbrain_api.models.cbrain_task import CbrainTask
from cbrain_api.models.cbrain_task_mod_req import CbrainTaskModReq
from cbrain_api.models.data_provider import DataProvider
from cbrain_api.models.file_info import FileInfo
from cbrain_api.models.group import Group
from cbrain_api.models.group_mod_req import GroupModReq
from cbrain_api.models.multi_registration_mod_req import MultiRegistrationModReq
from cbrain_api.models.multi_userfiles_mod_req import MultiUserfilesModReq
from cbrain_api.models.registration_info import RegistrationInfo
from cbrain_api.models.session_info import SessionInfo
from cbrain_api.models.tag import Tag
from cbrain_api.models.tag_mod_req import TagModReq
from cbrain_api.models.tool import Tool
from cbrain_api.models.tool_config import ToolConfig
from cbrain_api.models.user import User
from cbrain_api.models.user_mod_req import UserModReq
from cbrain_api.models.userfile import Userfile
from cbrain_api.models.userfile_mod_req import UserfileModReq
