# coding: utf-8

"""
    CBRAIN API

    API for interacting with the CBRAIN Platform  # noqa: E501

    OpenAPI spec version: 6.2.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from cbrain_api.configuration import Configuration


class Bourreau(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'user_id': 'int',
        'group_id': 'int',
        'online': 'str',
        'read_only': 'str',
        'description': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'user_id': 'user_id',
        'group_id': 'group_id',
        'online': 'online',
        'read_only': 'read_only',
        'description': 'description'
    }

    def __init__(self, id=None, name=None, user_id=None, group_id=None, online=None, read_only=None, description=None, _configuration=None):  # noqa: E501
        """Bourreau - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._name = None
        self._user_id = None
        self._group_id = None
        self._online = None
        self._read_only = None
        self._description = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if user_id is not None:
            self.user_id = user_id
        if group_id is not None:
            self.group_id = group_id
        if online is not None:
            self.online = online
        if read_only is not None:
            self.read_only = read_only
        if description is not None:
            self.description = description

    @property
    def id(self):
        """Gets the id of this Bourreau.  # noqa: E501

        Unique numerical ID for the bourreau.  # noqa: E501

        :return: The id of this Bourreau.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Bourreau.

        Unique numerical ID for the bourreau.  # noqa: E501

        :param id: The id of this Bourreau.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Bourreau.  # noqa: E501

        Name given by the creator to the bourreau.  # noqa: E501

        :return: The name of this Bourreau.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Bourreau.

        Name given by the creator to the bourreau.  # noqa: E501

        :param name: The name of this Bourreau.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def user_id(self):
        """Gets the user_id of this Bourreau.  # noqa: E501

        ID of the creator of the bourreau.  # noqa: E501

        :return: The user_id of this Bourreau.  # noqa: E501
        :rtype: int
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this Bourreau.

        ID of the creator of the bourreau.  # noqa: E501

        :param user_id: The user_id of this Bourreau.  # noqa: E501
        :type: int
        """

        self._user_id = user_id

    @property
    def group_id(self):
        """Gets the group_id of this Bourreau.  # noqa: E501

        ID of the group allowed to use the bourreau.  # noqa: E501

        :return: The group_id of this Bourreau.  # noqa: E501
        :rtype: int
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this Bourreau.

        ID of the group allowed to use the bourreau.  # noqa: E501

        :param group_id: The group_id of this Bourreau.  # noqa: E501
        :type: int
        """

        self._group_id = group_id

    @property
    def online(self):
        """Gets the online of this Bourreau.  # noqa: E501

        online  # noqa: E501

        :return: The online of this Bourreau.  # noqa: E501
        :rtype: str
        """
        return self._online

    @online.setter
    def online(self, online):
        """Sets the online of this Bourreau.

        online  # noqa: E501

        :param online: The online of this Bourreau.  # noqa: E501
        :type: str
        """

        self._online = online

    @property
    def read_only(self):
        """Gets the read_only of this Bourreau.  # noqa: E501

        Specifies whether the bourreau is read-only or can be modified.  # noqa: E501

        :return: The read_only of this Bourreau.  # noqa: E501
        :rtype: str
        """
        return self._read_only

    @read_only.setter
    def read_only(self, read_only):
        """Sets the read_only of this Bourreau.

        Specifies whether the bourreau is read-only or can be modified.  # noqa: E501

        :param read_only: The read_only of this Bourreau.  # noqa: E501
        :type: str
        """

        self._read_only = read_only

    @property
    def description(self):
        """Gets the description of this Bourreau.  # noqa: E501

        Description of the bourreau.  # noqa: E501

        :return: The description of this Bourreau.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this Bourreau.

        Description of the bourreau.  # noqa: E501

        :param description: The description of this Bourreau.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Bourreau, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Bourreau):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Bourreau):
            return True

        return self.to_dict() != other.to_dict()
